/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

/**
 * Floor sale change from X-days vs X-days ago. (e.g. 7day floor sale vs floor sale 14 days ago)
 */
export interface FloorSaleChange {
  '1day'?: number;
  '30day'?: number;
  '7day'?: number;
}
