/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type GetCollectionsTrendingV1Period = typeof GetCollectionsTrendingV1Period[keyof typeof GetCollectionsTrendingV1Period];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCollectionsTrendingV1Period = {
  '5m': '5m',
  '10m': '10m',
  '30m': '30m',
  '1h': '1h',
  '6h': '6h',
  '1d': '1d',
  '24h': '24h',
  '7d': '7d',
  '30d': '30d',
} as const;
