/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetCollectionsActivityV6SortBy } from './getCollectionsActivityV6SortBy';
import type { GetCollectionsActivityV6TypesItem } from './getCollectionsActivityV6TypesItem';

export type GetCollectionsActivityV6Params = {
/**
 * Filter to a particular collection with collection-id. Example: `0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63`
 */
collection?: string;
/**
 * Filter to a particular collection set.
 */
collectionsSetId?: string;
/**
 * Filter to a particular community. Example: `artblocks`
 */
community?: string;
/**
 * Filter to a particular attribute. Note: Our docs do not support this parameter correctly. To test, you can use the following URL in your browser. Example: `https://api.reservoir.tools/collections/activity/v6?collection=0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63&attribute[Type]=Original` or `https://api.reservoir.tools/collections/activity/v6?collection=0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63&attribute[Type]=Original&attribute[Type]=Sibling`
 */
attributes?: string;
/**
 * If true, will filter any activities marked as spam.
 */
excludeSpam?: boolean;
/**
 * Amount of items returned. Max limit is 50 when `includedMetadata=true` otherwise max limit is 1000.
 */
limit?: number;
/**
 * Order the items are returned in the response. The blockchain event time is `eventTimestamp`. The event time recorded is `createdAt`.
 */
sortBy?: GetCollectionsActivityV6SortBy;
/**
 * Use continuation token to request next offset of items.
 */
continuation?: string;
/**
 * If true, metadata is included in the response. If true, max limit is 50.
 */
includeMetadata?: boolean;
types?: GetCollectionsActivityV6TypesItem[];
/**
 * Input any ERC20 address to return result in given currency
 */
displayCurrency?: string;
};
