/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetCollectionsTrendingmintsV1Period } from './getCollectionsTrendingmintsV1Period';
import type { GetCollectionsTrendingmintsV1Type } from './getCollectionsTrendingmintsV1Type';

export type GetCollectionsTrendingmintsV1Params = {
/**
 * Time window to aggregate.
 */
period?: GetCollectionsTrendingmintsV1Period;
/**
 * The type of the mint (free/paid).
 */
type?: GetCollectionsTrendingmintsV1Type;
/**
 * Amount of items returned in response. Default is 50 and max is 50. Expected to be sorted and filtered on client side.
 */
limit?: number;
/**
 * If true, prices will include missing royalties to be added on-top.
 */
normalizeRoyalties?: boolean;
/**
 * If true, return the non flagged floor ask. Supported only when `normalizeRoyalties` is false.
 */
useNonFlaggedFloorAsk?: boolean;
};
