/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type GetCollectionsV7SortBy = typeof GetCollectionsV7SortBy[keyof typeof GetCollectionsV7SortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCollectionsV7SortBy = {
  '1DayVolume': '1DayVolume',
  '7DayVolume': '7DayVolume',
  '30DayVolume': '30DayVolume',
  allTimeVolume: 'allTimeVolume',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  floorAskPrice: 'floorAskPrice',
} as const;
