/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetCollectionsV4SortBy } from './getCollectionsV4SortBy';

export type GetCollectionsV4Params = {
/**
 * Filter to a particular collection set.
 */
collectionsSetId?: string;
/**
 * Filter to a particular community. Example: `artblocks`
 */
community?: string;
contract?: string[];
/**
 * Search for collections that match a string. Example: `bored`
 */
name?: string;
/**
 * Filter to a particular collection slug. Example: `boredapeyachtclub`
 */
slug?: string;
/**
 * Order the items are returned in the response.
 */
sortBy?: GetCollectionsV4SortBy;
/**
 * If true, top bid will be returned in the response.
 */
includeTopBid?: boolean;
/**
 * Amount of items returned in response.
 */
limit?: number;
/**
 * Use continuation token to request next offset of items.
 */
continuation?: string;
};
