/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetCollectionsTrendingV1Period } from './getCollectionsTrendingV1Period';
import type { GetCollectionsTrendingV1SortBy } from './getCollectionsTrendingV1SortBy';

export type GetCollectionsTrendingV1Params = {
/**
 * Time window to aggregate.
 */
period?: GetCollectionsTrendingV1Period;
/**
 * Amount of items returned in response. Default is 50 and max is 1000. Expected to be sorted and filtered on client side.
 */
limit?: number;
sortBy?: GetCollectionsTrendingV1SortBy;
/**
 * If true, prices will include missing royalties to be added on-top.
 */
normalizeRoyalties?: boolean;
/**
 * If true, return the non flagged floor ask. Supported only when `normalizeRoyalties` is false.
 */
useNonFlaggedFloorAsk?: boolean;
};
