/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetCollectionsCollectionActivityV2SortBy } from './getCollectionsCollectionActivityV2SortBy';
import type { GetCollectionsCollectionActivityV2TypesItem } from './getCollectionsCollectionActivityV2TypesItem';

export type GetCollectionsCollectionActivityV2Params = {
/**
 * Amount of items returned in response. If `includeMetadata=true` max limit is 20, otherwise max limit is 1,000.
 */
limit?: number;
/**
 * Order the items are returned in the response, eventTimestamp = The blockchain event time, createdAt - The time in which event was recorded
 */
sortBy?: GetCollectionsCollectionActivityV2SortBy;
/**
 * Use continuation token to request next offset of items.
 */
continuation?: string;
/**
 * If true, metadata is included in the response.
 */
includeMetadata?: boolean;
types?: GetCollectionsCollectionActivityV2TypesItem[];
};
