/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetCollectionsTopsellingV2Period } from './getCollectionsTopsellingV2Period';
import type { GetCollectionsTopsellingV2FillType } from './getCollectionsTopsellingV2FillType';
import type { GetCollectionsTopsellingV2SortBy } from './getCollectionsTopsellingV2SortBy';

export type GetCollectionsTopsellingV2Params = {
/**
 * Time window to aggregate.
 */
period?: GetCollectionsTopsellingV2Period;
/**
 * Fill types to aggregate from (sale, mint, any)
 */
fillType?: GetCollectionsTopsellingV2FillType;
/**
 * Amount of items returned in response. Default is 25 and max is 50
 */
limit?: number;
sortBy?: GetCollectionsTopsellingV2SortBy;
/**
 * If true, 8 recent sales will be included in the response
 */
includeRecentSales?: boolean;
/**
 * If true, prices will include missing royalties to be added on-top.
 */
normalizeRoyalties?: boolean;
/**
 * If true, return the non flagged floor ask. Supported only when `normalizeRoyalties` is false.
 */
useNonFlaggedFloorAsk?: boolean;
};
