/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type GetCollectionsDailyvolumesV1Params = {
/**
 * Filter to a particular collection with collection-id. Example: `0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63`
 */
id: string;
/**
 * Amount of items returned in response.
 */
limit?: number;
/**
 * The start timestamp you want to filter on (UTC)
 */
startTimestamp?: number;
/**
 * The end timestamp you want to filter on (UTC)
 */
endTimestamp?: number;
};
