/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetCollectionsCollectionAttributesExploreV1SortBy } from './getCollectionsCollectionAttributesExploreV1SortBy';

export type GetCollectionsCollectionAttributesExploreV1Params = {
/**
 * Filter to a particular attribute key, e.g. `Composition`
 */
attributeKey?: string;
sortBy?: GetCollectionsCollectionAttributesExploreV1SortBy;
offset?: number;
limit?: number;
};
