/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type GetCollectionsActivityV5TypesItem = typeof GetCollectionsActivityV5TypesItem[keyof typeof GetCollectionsActivityV5TypesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCollectionsActivityV5TypesItem = {
  sale: 'sale',
  ask: 'ask',
  transfer: 'transfer',
  mint: 'mint',
  bid: 'bid',
  bid_cancel: 'bid_cancel',
  ask_cancel: 'ask_cancel',
} as const;
