/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type GetExecuteCancelV2Params = {
/**
 * Order Id. Example: `0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63`
 */
id: string;
/**
 * Optional. Set custom gas price
 */
maxFeePerGas?: string;
/**
 * Optional. Set custom gas price
 */
maxPriorityFeePerGas?: string;
};
