/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model482 } from './model482';
import type { MaxQuantities } from './maxQuantities';
import type { Model486 } from './model486';
import type { Model480 } from './model480';

export interface GetExecuteBuyV7Response {
  errors?: Model482;
  gasEstimate?: number;
  maxQuantities?: MaxQuantities;
  path?: Model486;
  requestId?: string;
  steps?: Model480;
}
