/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetOrdersUsersUserTopbidsV3SortBy } from './getOrdersUsersUserTopbidsV3SortBy';
import type { GetOrdersUsersUserTopbidsV3SortDirection } from './getOrdersUsersUserTopbidsV3SortDirection';

export type GetOrdersUsersUserTopbidsV3Params = {
collection?: string;
/**
 * Filter to a particular contracts set.
 */
contractsSetId?: string;
/**
 * Filter to a particular community. Example: `artblocks`
 */
community?: string;
/**
 * Filter to a particular collection set.
 */
collectionsSetId?: string;
/**
 * If true, urls will only be returned for optimized sources that support royalties.
 */
optimizeCheckoutURL?: boolean;
/**
 * If true, criteria metadata is included in the response.
 */
includeCriteriaMetadata?: boolean;
/**
 * If true, prices will include missing royalties to be added on-top.
 */
normalizeRoyalties?: boolean;
/**
 * If true, will return the collection non flagged floor ask events.
 */
useNonFlaggedFloorAsk?: boolean;
/**
 * Use continuation token to request next offset of items.
 */
continuation?: string;
/**
 * Order of the items are returned in the response.
 */
sortBy?: GetOrdersUsersUserTopbidsV3SortBy;
sortDirection?: GetOrdersUsersUserTopbidsV3SortDirection;
/**
 * Amount of items returned in response.
 */
limit?: number;
/**
 * Amount of tokens considered.
 */
sampleSize?: number;
/**
 * Return result in given currency
 */
displayCurrency?: string;
};
