/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetOrdersUsersUserTopbidsV1SortBy } from './getOrdersUsersUserTopbidsV1SortBy';
import type { GetOrdersUsersUserTopbidsV1SortDirection } from './getOrdersUsersUserTopbidsV1SortDirection';

export type GetOrdersUsersUserTopbidsV1Params = {
collection?: string;
/**
 * Filter to a particular community. Example: `artblocks`
 */
community?: string;
/**
 * If true, urls will only be returned for optimized sources that support royalties.
 */
optimizeCheckoutURL?: boolean;
/**
 * If true, prices will include missing royalties to be added on-top.
 */
normalizeRoyalties?: boolean;
/**
 * Use continuation token to request next offset of items.
 */
continuation?: string;
/**
 * Order of the items are returned in the response.
 */
sortBy?: GetOrdersUsersUserTopbidsV1SortBy;
sortDirection?: GetOrdersUsersUserTopbidsV1SortDirection;
/**
 * Amount of items returned in response.
 */
limit?: number;
};
