/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type GetOrdersAsksV5SortBy = typeof GetOrdersAsksV5SortBy[keyof typeof GetOrdersAsksV5SortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetOrdersAsksV5SortBy = {
  createdAt: 'createdAt',
  price: 'price',
  updatedAt: 'updatedAt',
} as const;
