/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetOrdersAllV1Side } from './getOrdersAllV1Side';

export type GetOrdersAllV1Params = {
id?: string;
/**
 * Filter to a source by domain. Example: `opensea.io`
 */
source?: string;
/**
 * If true, results will filter only Reservoir orders.
 */
native?: boolean;
/**
 * Sell or buy side.
 */
side?: GetOrdersAllV1Side;
/**
 * If true, metadata will be included in the response.
 */
includeMetadata?: boolean;
/**
 * If true, raw data will be included in the response.
 */
includeRawData?: boolean;
/**
 * Use continuation token to request next offset of items.
 */
continuation?: string;
/**
 * Amount of items returned in response.
 */
limit?: number;
};
