/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetOrdersUsersUserTopbidsV4SortBy } from './getOrdersUsersUserTopbidsV4SortBy';
import type { GetOrdersUsersUserTopbidsV4SortDirection } from './getOrdersUsersUserTopbidsV4SortDirection';

export type GetOrdersUsersUserTopbidsV4Params = {
collection?: string;
/**
 * Filter to a particular contracts set.
 */
contractsSetId?: string;
/**
 * Filter to a particular community. Example: `artblocks`
 */
community?: string;
/**
 * Filter to a particular collection set. Example: `8daa732ebe5db23f267e58d52f1c9b1879279bcdf4f78b8fb563390e6946ea65`
 */
collectionsSetId?: string;
/**
 * If true, urls will only be returned for optimized sources that support royalties.
 */
optimizeCheckoutURL?: boolean;
/**
 * If true, criteria metadata is included in the response.
 */
includeCriteriaMetadata?: boolean;
/**
 * Exclude orders that can only be filled by EOAs, to support filling with smart contracts.
 */
excludeEOA?: boolean;
/**
 * If true, prices will include missing royalties to be added on-top.
 */
normalizeRoyalties?: boolean;
/**
 * If true, will return the collection non flagged floor ask events.
 */
useNonFlaggedFloorAsk?: boolean;
/**
 * Use continuation token to request next offset of items.
 */
continuation?: string;
/**
 * Order of the items are returned in the response. Options are `topBidValue`, `dateCreated`, `orderExpiry`, and `floorDifferencePercentage`.
 */
sortBy?: GetOrdersUsersUserTopbidsV4SortBy;
sortDirection?: GetOrdersUsersUserTopbidsV4SortDirection;
/**
 * Amount of items returned in response. Max limit is 100
 */
limit?: number;
/**
 * Amount of tokens considered. Min is 1000, max is default.
 */
sampleSize?: number;
/**
 * Input any ERC20 address to return result in given currency
 */
displayCurrency?: string;
};
