/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type GetOrdersUsersUserTopbidsV1SortBy = typeof GetOrdersUsersUserTopbidsV1SortBy[keyof typeof GetOrdersUsersUserTopbidsV1SortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetOrdersUsersUserTopbidsV1SortBy = {
  topBidValue: 'topBidValue',
  dateCreated: 'dateCreated',
  orderExpiry: 'orderExpiry',
  floorDifferencePercentage: 'floorDifferencePercentage',
} as const;
