/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetOrdersAsksV1Status } from './getOrdersAsksV1Status';
import type { GetOrdersAsksV1SortBy } from './getOrdersAsksV1SortBy';

export type GetOrdersAsksV1Params = {
/**
 * Filter to a token, e.g. `0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63:123`
 */
token?: string;
/**
 * Filter to a particular user, e.g. `0x4d04eb67a2d1e01c71fad0366e0c200207a75487`
 */
maker?: string;
/**
 * Filter to a particular user, e.g. `0x4d04eb67a2d1e01c71fad0366e0c200207a75487`
 */
contract?: string;
/**
 * `active` = currently valid, `inactive` = temporarily invalid

Available when filtering by maker, otherwise only valid orders will be returned
 */
status?: GetOrdersAsksV1Status;
sortBy?: GetOrdersAsksV1SortBy;
continuation?: string;
limit?: number;
};
