/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetOracleCollectionsBidaskmidpointV1Kind } from './getOracleCollectionsBidaskmidpointV1Kind';
import type { GetOracleCollectionsBidaskmidpointV1Signer } from './getOracleCollectionsBidaskmidpointV1Signer';

export type GetOracleCollectionsBidaskmidpointV1Params = {
kind?: GetOracleCollectionsBidaskmidpointV1Kind;
currency?: string;
twapSeconds?: number;
collection?: string;
token?: string;
signer?: GetOracleCollectionsBidaskmidpointV1Signer;
};
