/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetOracleCollectionsFlooraskV6Kind } from './getOracleCollectionsFlooraskV6Kind';
import type { GetOracleCollectionsFlooraskV6Signer } from './getOracleCollectionsFlooraskV6Signer';

export type GetOracleCollectionsFlooraskV6Params = {
kind?: GetOracleCollectionsFlooraskV6Kind;
currency?: string;
twapSeconds?: number;
eip3668Calldata?: string;
collection?: string;
token?: string;
/**
 * If true, will use the collection non flagged floor ask events.
 */
useNonFlaggedFloorAsk?: boolean;
signer?: GetOracleCollectionsFlooraskV6Signer;
};
