/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type GetOracleCollectionsFlooraskV5Signer = typeof GetOracleCollectionsFlooraskV5Signer[keyof typeof GetOracleCollectionsFlooraskV5Signer];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetOracleCollectionsFlooraskV5Signer = {
  '0x32da57e736e05f75aa4fae2e9be60fd904492726': '0x32da57e736e05f75aa4fae2e9be60fd904492726',
  '0xaeb1d03929bf87f69888f381e73fbf75753d75af': '0xaeb1d03929bf87f69888f381e73fbf75753d75af',
} as const;
