/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetOrdersDepthV1Side } from './getOrdersDepthV1Side';

export type GetOrdersDepthV1Params = {
side: GetOrdersDepthV1Side;
/**
 * Filter to a particular token. Example: `0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63:123`.
 */
token?: string;
/**
 * Filter to a particular collection. Example: `0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63`.
 */
collection?: string;
/**
 * Return all prices in this currency.
 */
displayCurrency?: string;
};
