/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetSearchActivitiesV1SortBy } from './getSearchActivitiesV1SortBy';
import type { GetSearchActivitiesV1TypesItem } from './getSearchActivitiesV1TypesItem';

export type GetSearchActivitiesV1Params = {
/**
 * Array of tokens. Max limit is 50. Example: `tokens[0]: 0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63:704 tokens[1]: 0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63:979`
 */
tokens?: string[];
/**
 * Array of collections. Max limit is 50. Example: `collections[0]: 0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63`
 */
collections?: string[];
/**
 * Filter to a particular contracts set.
 */
contractsSetId?: string;
/**
 * Filter to a particular collection set.
 */
collectionsSetId?: string;
/**
 * Filter to a particular community. Example: `artblocks`
 */
community?: string;
/**
 * Filter to a particular attribute. Note: Our docs do not support this parameter correctly. To test, you can use the following URL in your browser. Example: `https://api.reservoir.tools/collections/activity/v6?collection=0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63&attribute[Type]=Original` or `https://api.reservoir.tools/collections/activity/v6?collection=0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63&attribute[Type]=Original&attribute[Type]=Sibling`
 */
attributes?: string;
/**
 * Array of source domains. Max limit is 50. Example: `sources[0]: opensea.io`
 */
sources?: string[];
/**
 * Array of users addresses. Max is 50. Example: `0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63`
 */
users?: string[];
/**
 * Amount of items returned. Max limit is 50 when `includedMetadata=true` otherwise max limit is 1000.
 */
limit?: number;
/**
 * Order the items are returned in the response. The blockchain event time is `timestamp`. The event time recorded is `createdAt`.
 */
sortBy?: GetSearchActivitiesV1SortBy;
/**
 * Use continuation token to request next offset of items.
 */
continuation?: string;
types?: GetSearchActivitiesV1TypesItem[];
/**
 * Input any ERC20 address to return result in given currency
 */
displayCurrency?: string;
};
