/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetSourcesV1SortBy } from './getSourcesV1SortBy';
import type { GetSourcesV1SortDirection } from './getSourcesV1SortDirection';

export type GetSourcesV1Params = {
/**
 * Order of the items are returned in the response.
 */
sortBy?: GetSourcesV1SortBy;
/**
 * Order the items are returned in the response.
 */
sortDirection?: GetSourcesV1SortDirection;
/**
 * Filter to a particular domain. Example: `x2y2.io`
 */
domain?: string;
/**
 * Amount of items returned in response.
 */
limit?: number;
continuation?: string;
};
