/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type GetSearchCollectionsV2Params = {
/**
 * Lightweight search for collections that match a string. Example: `bored`
 */
name?: string;
/**
 * Filter to a particular community. Example: `artblocks`
 */
community?: string;
/**
 * Return result in given currency
 */
displayCurrency?: string;
/**
 * Filter to a particular collection set
 */
collectionsSetId?: string;
/**
 * If true, will filter any collections marked as spam.
 */
excludeSpam?: boolean;
/**
 * Use offset to request the next batch of items.
 */
offset?: number;
/**
 * Amount of items returned in response.
 */
limit?: number;
};
