/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetSalesV4OrderBy } from './getSalesV4OrderBy';
import type { GetSalesV4SortDirection } from './getSalesV4SortDirection';

export type GetSalesV4Params = {
contract?: string[];
/**
 * Filter to a particular token. Example: `0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63:123`
 */
token?: string;
/**
 * If enabled, also include token metadata in the response.
 */
includeTokenMetadata?: boolean;
/**
 * If enabled, include sales that have been deleted. In some cases the backfilling process deletes sales that are no longer relevant or have been reverted.
 */
includeDeleted?: boolean;
/**
 * Filter to a particular collection with collection-id. Example: `0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63`
 */
collection?: string;
/**
 * Filter to a particular attribute. Note: Our docs do not support this parameter correctly. To test, you can use the following URL in your browser. Example: `https://api.reservoir.tools/sales/v4?collection=0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63&attributes[Type]=Original` or `https://api.reservoir.tools/sales/v4?collection=0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63&attributes[Type]=Original&attributes[Type]=Sibling`
 */
attributes?: string;
/**
 * Order the items are returned in the response.
 */
orderBy?: GetSalesV4OrderBy;
/**
 * Order the items are returned in the response.
 */
sortDirection?: GetSalesV4SortDirection;
/**
 * Filter to a particular transaction. Example: `0x04654cc4c81882ed4d20b958e0eeb107915d75730110cce65333221439de6afc`
 */
txHash?: string;
/**
 * Get events after a particular unix timestamp (inclusive). Relative to the orderBy time filters.
 */
startTimestamp?: number;
/**
 * Get events before a particular unix timestamp (inclusive). Relative to the orderBy time filters.
 */
endTimestamp?: number;
/**
 * Amount of items returned in response.
 */
limit?: number;
/**
 * Use continuation token to request next offset of items.
 */
continuation?: string;
};
