/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetSalesV6SortBy } from './getSalesV6SortBy';
import type { GetSalesV6SortDirection } from './getSalesV6SortDirection';

export type GetSalesV6Params = {
contract?: string[];
/**
 * Array of tokens. Max limit is 20. Example: `tokens[0]: 0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63:704tokens[1]: 0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63:979`
 */
tokens?: string[];
/**
 * If enabled, also include token metadata in the response. Default is false.
 */
includeTokenMetadata?: boolean;
/**
 * If enabled, include sales that have been deleted. In some cases the backfilling process deletes sales that are no longer relevant or have been reverted.
 */
includeDeleted?: boolean;
/**
 * Filter to a particular collection with collection-id. Example: `0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63`
 */
collection?: string;
/**
 * Filter to a particular attribute. Attributes are case sensitive. Note: Our docs do not support this parameter correctly. To test, you can use the following URL in your browser. Example: `https://api.reservoir.tools/sales/v6?collection=0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63&attributes[Type]=Original` or `https://api.reservoir.tools/sales/v6?collection=0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63&attributes[Type]=Original&attributes[Type]=Sibling`
 */
attributes?: string;
/**
 * Order the items are returned in the response. Options are `price`, `time`, and `updatedAt`. Default is `time`.
 */
sortBy?: GetSalesV6SortBy;
/**
 * Order the items are returned in the response.
 */
sortDirection?: GetSalesV6SortDirection;
/**
 * Filter to a particular transaction. Example: `0x04654cc4c81882ed4d20b958e0eeb107915d75730110cce65333221439de6afc`
 */
txHash?: string;
/**
 * Get events after a particular unix timestamp (inclusive). Relative to the sortBy time filters.
 */
startTimestamp?: number;
/**
 * Get events before a particular unix timestamp (inclusive). Relative to the sortBy time filters.
 */
endTimestamp?: number;
/**
 * Amount of items returned in response. Max limit is 1000.
 */
limit?: number;
/**
 * Use continuation token to request next offset of items.
 */
continuation?: string;
};
