/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type GetTokensTokenActivityV2SortBy = typeof GetTokensTokenActivityV2SortBy[keyof typeof GetTokensTokenActivityV2SortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetTokensTokenActivityV2SortBy = {
  eventTimestamp: 'eventTimestamp',
  createdAt: 'createdAt',
} as const;
