/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetTokensTokenActivityV5SortBy } from './getTokensTokenActivityV5SortBy';
import type { GetTokensTokenActivityV5TypesItem } from './getTokensTokenActivityV5TypesItem';

export type GetTokensTokenActivityV5Params = {
/**
 * Amount of items returned. Default and max is 20.
 */
limit?: number;
/**
 * Order the items are returned in the response. The blockchain event time is `eventTimestamp`. The event time recorded is `createdAt`.
 */
sortBy?: GetTokensTokenActivityV5SortBy;
/**
 * If true, metadata is included in the response.
 */
includeMetadata?: boolean;
/**
 * Use continuation token to request next offset of items.
 */
continuation?: string;
/**
 * If true, will filter any activities marked as spam.
 */
excludeSpam?: boolean;
types?: GetTokensTokenActivityV5TypesItem[];
/**
 * Input any ERC20 address to return result in given currency
 */
displayCurrency?: string;
};
