/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetTokensTokenActivityV2SortBy } from './getTokensTokenActivityV2SortBy';
import type { GetTokensTokenActivityV2TypesItem } from './getTokensTokenActivityV2TypesItem';

export type GetTokensTokenActivityV2Params = {
/**
 * Amount of items returned in response.
 */
limit?: number;
/**
 * Order the items are returned in the response, eventTimestamp = The blockchain event time, createdAt - The time in which event was recorded
 */
sortBy?: GetTokensTokenActivityV2SortBy;
/**
 * Use continuation token to request next offset of items.
 */
continuation?: string;
types?: GetTokensTokenActivityV2TypesItem[];
};
