/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type GetTokensV7FlagStatus = typeof GetTokensV7FlagStatus[keyof typeof GetTokensV7FlagStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetTokensV7FlagStatus = {
  NUMBER_MINUS_1: -1,
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
