/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetTokensDetailsV3SortBy } from './getTokensDetailsV3SortBy';

export type GetTokensDetailsV3Params = {
/**
 * Filter to a particular collection, e.g. `0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63`
 */
collection?: string;
/**
 * Filter to a particular contract, e.g. `0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63`
 */
contract?: string;
/**
 * Filter to one or more tokens, e.g. `0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63:123`
 */
tokens?: string[];
/**
 * Filter to a particular set, e.g. `contract:0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63`
 */
tokenSetId?: string;
/**
 * Filter to a particular attribute, e.g. `attributes[Type]=Original`
 */
attributes?: string;
/**
 * Filter to a particular source, e.g. `0x5b3256965e7c3cf26e11fcaf296dfc8807c01073`
 */
source?: string;
sortBy?: GetTokensDetailsV3SortBy;
limit?: number;
continuation?: string;
};
