/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetTokensV6FlagStatus } from './getTokensV6FlagStatus';
import type { GetTokensV6SortBy } from './getTokensV6SortBy';
import type { GetTokensV6SortDirection } from './getTokensV6SortDirection';

export type GetTokensV6Params = {
/**
 * Filter to a particular collection with collection-id. Example: `0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63`
 */
collection?: string;
/**
 * Filter to a particular token by name. This is case sensitive. Example: `token #1`
 */
tokenName?: string;
/**
 * Array of tokens. Max limit is 50. Example: `tokens[0]: 0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63:704 tokens[1]: 0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63:979`
 */
tokens?: string[];
/**
 * Filter to a particular attribute. Attributes are case sensitive. Note: Our docs do not support this parameter correctly. To test, you can use the following URL in your browser. Example: `https://api.reservoir.tools/tokens/v6?collection=0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63&attributes[Type]=Original` or `https://api.reservoir.tools/tokens/v6?collection=0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63&attributes[Type]=Original&attributes[Type]=Sibling`
 */
attributes?: string;
/**
 * Domain of the order source. Example `opensea.io` (Only listed tokens are returned when filtering by source)
 */
source?: string;
/**
 * Domain of the order source. Example `www.apecoinmarketplace.com`. For a native marketplace, return all tokens listed on this marketplace, even if better prices are available on other marketplaces.
 */
nativeSource?: string;
/**
 * Get tokens with a min rarity rank (inclusive), no rarity rank for collections over 100k
 */
minRarityRank?: number;
/**
 * Get tokens with a max rarity rank (inclusive), no rarity rank for collections over 100k
 */
maxRarityRank?: number;
/**
 * Get tokens with a min floor ask price (inclusive); use native currency
 */
minFloorAskPrice?: number;
/**
 * Get tokens with a max floor ask price (inclusive); use native currency
 */
maxFloorAskPrice?: number;
/**
 * Allowed only with collection and tokens filtering!
-1 = All tokens (default)
0 = Non flagged tokens
1 = Flagged tokens
 */
flagStatus?: GetTokensV6FlagStatus;
/**
 * Filter to a particular collection set. Example: `8daa732ebe5db23f267e58d52f1c9b1879279bcdf4f78b8fb563390e6946ea65`
 */
collectionsSetId?: string;
/**
 * Filter to a particular community. Example: `artblocks`
 */
community?: string;
contract?: string[];
/**
 * Filter to a particular token set. `Example: token:0xa7d8d9ef8d8ce8992df33d8b8cf4aebabd5bd270:129000685`
 */
tokenSetId?: string;
/**
 * Order the items are returned in the response. Options are `floorAskPrice`, `tokenId`, `rarity`, and `updatedAt`. No rarity rank for collections over 100k.
 */
sortBy?: GetTokensV6SortBy;
sortDirection?: GetTokensV6SortDirection;
/**
 * Filter to tokens with a listing in a particular currency. Max limit is 50. `Example: currencies[0]: 0x0000000000000000000000000000000000000000`
 */
currencies?: string[];
/**
 * Amount of items returned in response. Max limit is 100, except when sorting by `updatedAt` which has a limit of 1000.
 */
limit?: number;
/**
 * When sorting by `updatedAt`, the start timestamp you want to filter on (UTC).
 */
startTimestamp?: number;
/**
 * When sorting by `updatedAt`, the end timestamp you want to filter on (UTC).
 */
endTimestamp?: number;
/**
 * If true, top bid will be returned in the response.
 */
includeTopBid?: boolean;
/**
 * If true, mint data for the tokens will be included in the response.
 */
includeMintStages?: boolean;
/**
 * Exclude orders that can only be filled by EOAs, to support filling with smart contracts. defaults to false
 */
excludeEOA?: boolean;
/**
 * If true, will filter any tokens marked as spam.
 */
excludeSpam?: boolean;
/**
 * Exclude orders that have been burned, defaults to false
 */
excludeBurns?: boolean;
/**
 * If true, attributes will be returned in the response.
 */
includeAttributes?: boolean;
/**
 * If true, quantity filled and quantity remaining will be returned in the response.
 */
includeQuantity?: boolean;
/**
 * If true, dynamic pricing data will be returned in the response.
 */
includeDynamicPricing?: boolean;
/**
 * If true, last sale data including royalties paid will be returned in the response.
 */
includeLastSale?: boolean;
/**
 * If true, prices will include missing royalties to be added on-top.
 */
normalizeRoyalties?: boolean;
/**
 * Use continuation token to request next offset of items.
 */
continuation?: string;
/**
 * Input any ERC20 address to return result in given currency. Applies to `topBid` and `floorAsk`.
 */
displayCurrency?: string;
};
