/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type GetTokensV6SortBy = typeof GetTokensV6SortBy[keyof typeof GetTokensV6SortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetTokensV6SortBy = {
  floorAskPrice: 'floorAskPrice',
  tokenId: 'tokenId',
  rarity: 'rarity',
  updatedAt: 'updatedAt',
} as const;
