/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type GetTransfersBulkV1OrderBy = typeof GetTransfersBulkV1OrderBy[keyof typeof GetTransfersBulkV1OrderBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetTransfersBulkV1OrderBy = {
  timestamp: 'timestamp',
  updated_at: 'updated_at',
} as const;
