/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type GetUsersUserPositionsV1Status = typeof GetUsersUserPositionsV1Status[keyof typeof GetUsersUserPositionsV1Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUsersUserPositionsV1Status = {
  valid: 'valid',
  invalid: 'invalid',
} as const;
