/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { GetUsersUserTokensV1SortBy } from './getUsersUserTokensV1SortBy';
import type { GetUsersUserTokensV1SortDirection } from './getUsersUserTokensV1SortDirection';

export type GetUsersUserTokensV1Params = {
/**
 * Filter to a particular community, e.g. `artblocks`
 */
community?: string;
/**
 * Filter to a particular collection, e.g. `0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63`
 */
collection?: string;
/**
 * Filter to a particular contract, e.g. `0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63`
 */
contract?: string;
hasOffer?: boolean;
sortBy?: GetUsersUserTokensV1SortBy;
sortDirection?: GetUsersUserTokensV1SortDirection;
offset?: number;
limit?: number;
};
