/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Attribute } from './attribute';
import type { BulkData } from './bulkData';
import type { Model422 } from './model422';
import type { Model424Orderbook } from './model424Orderbook';

export interface Model424 {
  attribute?: Attribute;
  bulkData?: BulkData;
  collection?: string;
  isNonFlagged?: boolean;
  order?: Model422;
  orderbook?: Model424Orderbook;
  /** Optional API key for the target orderbook */
  orderbookApiKey?: string;
  permitId?: string;
  permitIndex?: number;
  tokenSetId?: string;
}
