/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Check } from './check';
import type { Metadata } from './metadata';
import type { SampleImages } from './sampleImages';
import type { Model477Status } from './model477Status';

export interface Model477 {
  check?: Check;
  data?: Metadata;
  /** Approximation of gas used (only applies to `transaction` items) */
  gasEstimate?: number;
  orderIds?: SampleImages;
  /** Response is `complete` or `incomplete`. */
  status: Model477Status;
  tip?: string;
}
