/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

/**
 * Execution kind
 */
export type Model537Kind = typeof Model537Kind[keyof typeof Model537Kind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Model537Kind = {
  'cross-chain-intent': 'cross-chain-intent',
  'cross-chain-transaction': 'cross-chain-transaction',
  'seaport-intent': 'seaport-intent',
  transaction: 'transaction',
} as const;
