/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model52 } from './model52';
import type { Model53OrderSide } from './model53OrderSide';
import type { Price } from './price';
import type { Model45 } from './model45';

export interface Model53 {
  amount?: string;
  batchIndex?: number;
  block?: number;
  /** Time when added to indexer */
  createdAt?: string;
  feeBreakdown?: Model52;
  fillSource?: string;
  from?: string;
  /** Deprecated. Use `saleId` instead. */
  id?: string;
  isDeleted?: boolean;
  logIndex?: number;
  marketplaceFeeBps?: number;
  orderId?: string;
  orderKind?: string;
  /** Can be `ask` or `bid`. */
  orderSide?: Model53OrderSide;
  orderSource?: string;
  paidFullRoyalty?: boolean;
  price?: Price;
  royaltyFeeBps?: number;
  /** Unique identifier made from txn hash, price, etc. */
  saleId?: string;
  /** Time added on the blockchain */
  timestamp?: number;
  to?: string;
  token?: Model45;
  txHash?: string;
  /** Time when updated in indexer */
  updatedAt?: string;
  washTradingScore?: number;
}
