/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model537Kind } from './model537Kind';

export interface Model537 {
  /** Chain id where the action is happening (only relevant for 'cross-chain-transaction' actions) */
  chainId?: number;
  /** The id of the execution (eg. transaction / order / intent hash) */
  id: string;
  /** Execution kind */
  kind: Model537Kind;
}
