/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type Model422Kind = typeof Model422Kind[keyof typeof Model422Kind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Model422Kind = {
  blur: 'blur',
  opensea: 'opensea',
  'looks-rare-v2': 'looks-rare-v2',
  'zeroex-v4': 'zeroex-v4',
  seaport: 'seaport',
  'seaport-v14': 'seaport-v1.4',
  'seaport-v15': 'seaport-v1.5',
  x2y2: 'x2y2',
  alienswap: 'alienswap',
  'payment-processor': 'payment-processor',
  'payment-processor-v2': 'payment-processor-v2',
} as const;
