/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model357Kind } from './model357Kind';
import type { Model356 } from './model356';

export interface Model357 {
  attributeCount?: number;
  key: string;
  kind: Model357Kind;
  maxRange?: number;
  minRange?: number;
  values?: Model356;
}
