/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model230 } from './model230';
import type { Source } from './source';
import type { Model113 } from './model113';
import type { Model110 } from './model110';
import type { Model284 } from './model284';

export interface Model285 {
  amount?: number;
  batchIndex?: number;
  collection?: Model230;
  contract?: string;
  /** Time when added in the indexer. */
  createdAt?: string;
  fillSource?: Source;
  fromAddress?: string;
  logIndex?: number;
  order?: Model113;
  price?: Model110;
  /** Time when added on the blockchain. */
  timestamp?: number;
  toAddress?: string;
  token?: Model284;
  /** Txn hash from the blockchain. */
  txHash?: string;
  /** Possible types returned: `ask`, `ask_cancel`, `bid`, `bid_cancel`, `sale`, `mint, and `transfer`. */
  type?: string;
}
