/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model47OrderSide } from './model47OrderSide';
import type { Model45 } from './model45';

export interface Model47 {
  amount?: string;
  from?: string;
  orderSide?: Model47OrderSide;
  price?: number;
  timestamp?: number;
  to?: string;
  token?: Model45;
  txHash?: string;
}
