/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Alienswap } from './alienswap';
import type { PaymentProcessorV2 } from './paymentProcessorV2';
import type { SeaportV14 } from './seaportV14';

/**
 * Additional options.
 */
export interface Model502 {
  alienswap?: Alienswap;
  'payment-processor-v2'?: PaymentProcessorV2;
  'seaport-v1.4'?: SeaportV14;
  'seaport-v1.5'?: SeaportV14;
}
