/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Price } from './price';
import type { Metadata } from './metadata';
import type { Source } from './source';

/**
 * Can be null if no asks.
 */
export interface Model339 {
  id?: string;
  isNativeOffChainCancellable?: boolean;
  kind?: string;
  maker?: string;
  price?: Price;
  rawData?: Metadata;
  source?: Source;
  validFrom?: number;
  validUntil?: number;
}
