/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model106 } from './model106';
import type { Depth } from './depth';
import type { Model166 } from './model166';
import type { Model168 } from './model168';
import type { Model110 } from './model110';
import type { Metadata } from './metadata';
import type { Model170Side } from './model170Side';

export interface Model170 {
  contract?: string;
  contractKind?: string;
  /** Time when added to indexer */
  createdAt: string;
  criteria?: Model106;
  depth?: Depth;
  dynamicPricing?: Model166;
  expiration: number;
  feeBps?: number;
  feeBreakdown?: Model168;
  id: string;
  isDynamic?: boolean;
  isNativeOffChainCancellable?: boolean;
  isReservoir?: boolean;
  /** This is the `orderKind`. */
  kind: string;
  maker: string;
  /** Time when created by maker */
  originatedAt?: string;
  price?: Model110;
  /** With ERC1155s, quantity can be higher than 1 */
  quantityFilled?: number;
  /** With ERC1155s, quantity can be higher than 1 */
  quantityRemaining?: number;
  rawData?: Metadata;
  /** Either `buy` or `sell` */
  side: Model170Side;
  source?: Metadata;
  /** Can be `active`, `inactive`, `expired`, `canceled`, or `filled` */
  status?: string;
  taker: string;
  tokenSetId: string;
  tokenSetSchemaHash: string;
  /** Time when updated in indexer */
  updatedAt: string;
  validFrom: number;
  validUntil: number;
}
