/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type Model49OrderSide = typeof Model49OrderSide[keyof typeof Model49OrderSide];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Model49OrderSide = {
  ask: 'ask',
  bid: 'bid',
} as const;
