/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model184OrderSide } from './model184OrderSide';
import type { Model183 } from './model183';

export interface Model184 {
  amount?: string;
  batchIndex?: number;
  fillSource?: string;
  from?: string;
  id?: string;
  logIndex?: number;
  orderKind?: string;
  orderSide?: Model184OrderSide;
  orderSource?: string;
  orderSourceDomain?: string;
  price?: number;
  saleId?: string;
  timestamp?: number;
  to?: string;
  token?: Model183;
  txHash?: string;
}
