/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model106 } from './model106';
import type { Model113Side } from './model113Side';
import type { Metadata } from './metadata';

export interface Model113 {
  criteria?: Model106;
  id?: string;
  side?: Model113Side;
  source?: Metadata;
}
