/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type Model81Kind = typeof Model81Kind[keyof typeof Model81Kind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Model81Kind = {
  dutch: 'dutch',
  pool: 'pool',
} as const;
