/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { AlternativeCurrencies } from './alternativeCurrencies';
import type { Model515 } from './model515';
import type { Model514 } from './model514';

export interface Model516 {
  alternativeCurrencies?: AlternativeCurrencies;
  /** Mint comment (where suported). */
  comment?: string;
  /** The chain id of the purchase currency. */
  currencyChainId?: number;
  feesOnTop?: Model515;
  items: Model514;
  /** If true, only the path will be returned. */
  onlyPath?: boolean;
  /** If true, any off-chain or on-chain errors will be skipped. */
  partial?: boolean;
  /** Referrer address (where supported). */
  referrer?: string;
  /** Address of wallet relaying the mint transaction(s) (paying for the NFT). */
  relayer?: string;
  /** If true, balance checks will be skipped. */
  skipBalanceCheck?: boolean;
  /** Filling source used for attribution. Example: `reservoir.market` */
  source?: string;
  /** Address of wallet minting (receiver of the NFT). */
  taker: string;
}
