/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Metadata } from './metadata';
import type { Model525Kind } from './model525Kind';

/**
 * Optional raw order to sell into.
 */
export interface Model525 {
  data?: Metadata;
  kind?: Model525Kind;
}
