/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model106 } from './model106';

export interface Model138 {
  contract?: string;
  criteria?: Model106;
  id?: string;
  kind?: string;
  maker?: string;
  nonce?: string;
  price?: number;
  quantityRemaining?: number;
  source?: string;
  status?: string;
  tokenSetId?: string;
  validFrom?: number;
  validUntil?: number;
  value?: number;
}
