/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export interface Model521 {
  /** Associated error message */
  errorMessage?: string;
  /** Request id of the associate execute API request */
  requestId: string;
  /** Step id of the relevant execute item */
  stepId: string;
  /** Associated transaction hash */
  txHash?: string;
}
