/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { FeesOnTop } from './feesOnTop';
import type { OrderIds } from './orderIds';
import type { RawOrders } from './rawOrders';
import type { Model458 } from './model458';

export interface Model459 {
  currency?: string;
  feesOnTop?: FeesOnTop;
  /** If true, all fills will be executed through the router. */
  forceRouter?: boolean;
  /** Optional. Set custom gas price. */
  maxFeePerGas?: string;
  /** Optional. Set custom gas price. */
  maxPriorityFeePerGas?: string;
  normalizeRoyalties?: boolean;
  /** If true, only the path will be returned. */
  onlyPath?: boolean;
  orderIds?: OrderIds;
  /** If true, any off-chain or on-chain errors will be skipped. */
  partial?: boolean;
  /** If there are multiple listings with equal best price, prefer this source over others.
NOTE: if you want to fill a listing that is not the best priced, you need to pass a specific order ID. */
  preferredOrderSource?: string;
  /** Quantity of tokens user is buying. Only compatible when buying a single ERC1155 token. Example: `5` */
  quantity?: number;
  rawOrders?: RawOrders;
  /** Address of wallet relaying the filling transaction */
  relayer?: string;
  /** If true, balance check will be skipped. */
  skipBalanceCheck?: boolean;
  /** Filling source used for attribution. Example: `reservoir.market` */
  source?: string;
  /** Address of wallet filling the order. Example: `0xF296178d553C8Ec21A2fBD2c5dDa8CA9ac905A00` */
  taker: string;
  tokens?: Model458;
  /** Override the X2Y2 API key used for filling. */
  x2y2ApiKey?: string;
}
