/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model453 } from './model453';
import type { Model454Kind } from './model454Kind';

export interface Model454 {
  action: string;
  description: string;
  /** Returns `currency-wrapping`, `currency-approval`, or `order-signature`. */
  id: string;
  items: Model453;
  /** Returns `request`, `signature`, or `transaction`. */
  kind: Model454Kind;
}
