/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model254 } from './model254';
import type { Model256 } from './model256';
import type { Model255 } from './model255';

export interface Model257 {
  collection?: Model254;
  event?: Model256;
  floorAsk?: Model255;
}
