/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model72 } from './model72';
import type { Model73 } from './model73';

export interface Model74 {
  floorAsk?: Model72;
  royaltiesPaid?: boolean;
  topBid?: Model73;
}
