/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Attribute } from './attribute';
import type { Model418 } from './model418';
import type { Model419Orderbook } from './model419Orderbook';

export interface Model419 {
  attribute?: Attribute;
  collection?: string;
  isNonFlagged?: boolean;
  order?: Model418;
  orderbook?: Model419Orderbook;
  orderbookApiKey?: string;
  /** The name of the source */
  source?: string;
  tokenSetId?: string;
}
