/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

/**
 * Optionally specify a particular fill method. Only relevant when filling via `collection`.
 */
export type Model474FillType = typeof Model474FillType[keyof typeof Model474FillType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Model474FillType = {
  trade: 'trade',
  mint: 'mint',
  preferMint: 'preferMint',
} as const;
