/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model201 } from './model201';
import type { Model64 } from './model64';
import type { LastBuy } from './lastBuy';

export interface Model207 {
  attributes?: Model201;
  collection?: Model64;
  contract: string;
  description?: string;
  image?: string;
  kind?: string;
  lastBuy?: LastBuy;
  lastSell?: LastBuy;
  name?: string;
  owner?: string;
  tokenId: string;
}
