/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

/**
 * Orderbook where order is placed. Example: `Reservoir`
 */
export type Model449Orderbook = typeof Model449Orderbook[keyof typeof Model449Orderbook];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Model449Orderbook = {
  blur: 'blur',
  reservoir: 'reservoir',
  opensea: 'opensea',
  'looks-rare': 'looks-rare',
  x2y2: 'x2y2',
} as const;
