/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model192 } from './model192';

export interface Model193 {
  allTimeVolume?: number;
  banner?: string;
  collectionId?: string;
  contract?: string;
  description?: string;
  floorAskPrice?: Model192;
  image?: string;
  isSpam?: boolean;
  metadataDisabled?: boolean;
  name?: string;
  openseaVerificationStatus?: string;
  slug?: string;
}
