/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export interface Model34 {
  /** Time when added to indexer */
  createdAt: string;
  id: number;
  orderbook: string;
  orderId: string;
  /** Possible values: pending - Waiting to be submitted. posted - Successfully submitted to the marketplace. posted - Failed to be submitted to the marketplace (see statusReason for detail). */
  status: string;
  statusReason: string;
  /** Time when updated in indexer */
  updatedAt: string;
}
