/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model339 } from './model339';

export interface Model340 {
  acquiredAt?: string;
  floorAsk?: Model339;
  onSaleCount?: string;
  tokenCount?: string;
}
