/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export interface Model440 {
  /** Refresh the given collection. Example: `0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63` */
  collection: string;
  /** If true, will force a refresh regardless of cool down. Requires an authorized api key to be passed. */
  overrideCoolDown?: boolean;
  /** If true, will refresh the metadata for the tokens in the collection. */
  refreshTokens?: boolean;
}
