/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type Model489OrderKind = typeof Model489OrderKind[keyof typeof Model489OrderKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Model489OrderKind = {
  blur: 'blur',
  seaport: 'seaport',
  'seaport-v14': 'seaport-v1.4',
  'seaport-v15': 'seaport-v1.5',
  'looks-rare-v2': 'looks-rare-v2',
  'zeroex-v4-erc721': 'zeroex-v4-erc721',
  'zeroex-v4-erc1155': 'zeroex-v4-erc1155',
  'payment-processor-v2': 'payment-processor-v2',
  rarible: 'rarible',
  alienswap: 'alienswap',
} as const;
