/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export interface Model190 {
  allTimeVolume?: number;
  banner?: string;
  collectionId?: string;
  contract?: string;
  description?: string;
  floorAskPrice?: number;
  image?: string;
  name?: string;
  openseaVerificationStatus?: string;
  tokenCount?: string;
}
