/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model64 } from './model64';

export interface Model67 {
  collection?: Model64;
  contract: string;
  floorAskPrice?: number;
  image?: string;
  isFlagged?: boolean;
  lastFlagUpdate?: string;
  media?: string;
  name?: string;
  owner?: string;
  rarity?: number;
  rarityRank?: number;
  source?: string;
  sourceDomain?: string;
  tokenId: string;
  topBidValue?: number;
}
