/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model70 } from './model70';
import type { Model64 } from './model64';
import type { LastBuy } from './lastBuy';

export interface Model71 {
  attributes?: Model70;
  collection?: Model64;
  contract: string;
  description?: string;
  image?: string;
  isFlagged?: boolean;
  kind?: string;
  lastBuy?: LastBuy;
  lastFlagChange?: string;
  lastFlagUpdate?: string;
  lastSell?: LastBuy;
  media?: string;
  name?: string;
  owner?: string;
  rarity?: number;
  rarityRank?: number;
  tokenId: string;
}
