/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type Model428Kind = typeof Model428Kind[keyof typeof Model428Kind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Model428Kind = {
  blur: 'blur',
  'zeroex-v4': 'zeroex-v4',
  x2y2: 'x2y2',
  'seaport-v14': 'seaport-v1.4',
  'seaport-v15': 'seaport-v1.5',
  element: 'element',
  rarible: 'rarible',
  manifold: 'manifold',
  'looks-rare-v2': 'looks-rare-v2',
} as const;
