/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

/**
 * Returns `request`, `signature`, or `transaction`.
 */
export type Model508Kind = typeof Model508Kind[keyof typeof Model508Kind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Model508Kind = {
  request: 'request',
  signature: 'signature',
  transaction: 'transaction',
} as const;
