/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Volume } from './volume';
import type { Model19 } from './model19';
import type { Model127 } from './model127';
import type { Model128MintType } from './model128MintType';
import type { SampleImages } from './sampleImages';
import type { Model28 } from './model28';

export interface Model128 {
  banner?: string;
  collectionVolume?: Volume;
  contract?: string;
  countPercentChange?: number;
  createdAt?: string;
  creator?: string;
  description?: string;
  endDate?: string;
  floorAsk?: Model19;
  /** Collection id */
  id?: string;
  image?: string;
  isSpam?: boolean;
  maxSupply?: number;
  mintCount?: number;
  mintPrice?: string;
  mintStages?: Model127;
  mintStatus?: string;
  mintType?: Model128MintType;
  mintVolume?: number;
  name?: string;
  oneHourCount?: number;
  onSaleCount?: number;
  openseaVerificationStatus?: string;
  /** Unique number of owners. */
  ownerCount?: number;
  primaryContract?: string;
  sampleImages?: SampleImages;
  sixHourCount?: number;
  startDate?: string;
  /** Total tokens within the collection. */
  tokenCount?: number;
  volumeChange?: Model28;
  volumePercentChange?: number;
}
