/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model183 } from './model183';

export interface Model218 {
  /** Can be more than 1 if erc1155. */
  amount?: string;
  batchIndex?: number;
  block?: number;
  from?: string;
  id?: string;
  isDeleted?: boolean;
  logIndex?: number;
  timestamp?: number;
  to?: string;
  token?: Model183;
  txHash?: string;
  /** Time when updated in indexer */
  updatedAt?: string;
}
