/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model106 } from './model106';
import type { Model107Side } from './model107Side';
import type { Source } from './source';

export interface Model107 {
  criteria?: Model106;
  id?: string;
  side?: Model107Side;
  source?: Source;
}
