/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model44 } from './model44';
import type { Model318 } from './model318';

export interface Model319 {
  collection?: Model44;
  contract?: string;
  image?: string;
  name?: string;
  tokenId?: string;
  topBid?: Model318;
}
