/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model287 } from './model287';

export interface Model374 {
  collection?: Model287;
  contract?: string;
  floorAskPrice?: number;
  image?: string;
  lastSalePrice?: number;
  name?: string;
  tokenId?: string;
}
