/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model256 } from './model256';
import type { Model269 } from './model269';
import type { Model183 } from './model183';

export interface Model270 {
  event?: Model256;
  floorAsk?: Model269;
  token?: Model183;
}
