/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model106 } from './model106';
import type { Model168 } from './model168';
import type { Model110 } from './model110';
import type { Source } from './source';
import type { Model371 } from './model371';

export interface Model372 {
  /** Time when added to indexer */
  createdAt?: string;
  criteria?: Model106;
  feeBreakdown?: Model168;
  /** Percentage difference between this bid and the current floor price. */
  floorDifferencePercentage?: number;
  id?: string;
  maker?: string;
  price?: Model110;
  source?: Source;
  token?: Model371;
  validFrom?: number;
  validUntil?: number;
}
