/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Metadata } from './metadata';
import type { Model81Kind } from './model81Kind';

/**
 * Can be null if no active ask.
 */
export interface Model81 {
  data?: Metadata;
  kind?: Model81Kind;
}
