/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model542 } from './model542';
import type { Model543Kind } from './model543Kind';

export interface Model543 {
  action: string;
  description: string;
  /** Returns `nft-approval` or `transfer` */
  id: string;
  items: Model542;
  /** Returns `transaction` */
  kind: Model543Kind;
}
