/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model79 } from './model79';
import type { Model77 } from './model77';
import type { Model53 } from './model53';
import type { Metadata } from './metadata';
import type { MintStages } from './mintStages';

export interface Model80 {
  attributes?: Model79;
  chainId: number;
  collection?: Model77;
  contract: string;
  description?: string;
  image?: string;
  imageLarge?: string;
  imageSmall?: string;
  isFlagged?: boolean;
  isSpam?: boolean;
  /** Can be erc721, erc115, etc. */
  kind?: string;
  lastFlagChange?: string;
  lastFlagUpdate?: string;
  lastSale?: Model53;
  media?: string;
  metadata?: Metadata;
  metadataDisabled?: boolean;
  mintStages?: MintStages;
  name?: string;
  owner?: string;
  /** No rarity for collections over 100k */
  rarity?: number;
  /** No rarity rank for collections over 100k */
  rarityRank?: number;
  remainingSupply?: number;
  /** Can be higher than 1 if erc1155 */
  supply?: number;
  tokenId: string;
}
