/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

/**
 * Exchange protocol used to bulk cancel order. Example: `seaport-v1.5`
 */
export type Model498OrderKind = typeof Model498OrderKind[keyof typeof Model498OrderKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Model498OrderKind = {
  'seaport-v14': 'seaport-v1.4',
  'seaport-v15': 'seaport-v1.5',
  alienswap: 'alienswap',
  'blur-bid': 'blur-bid',
  'payment-processor-v2': 'payment-processor-v2',
} as const;
