/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type Model465Kind = typeof Model465Kind[keyof typeof Model465Kind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Model465Kind = {
  opensea: 'opensea',
  'looks-rare': 'looks-rare',
  'zeroex-v4': 'zeroex-v4',
  seaport: 'seaport',
  'seaport-v14': 'seaport-v1.4',
  'seaport-v15': 'seaport-v1.5',
  x2y2: 'x2y2',
  rarible: 'rarible',
  sudoswap: 'sudoswap',
  nftx: 'nftx',
} as const;
