/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { CustomRoyalties } from './customRoyalties';
import type { Model448 } from './model448';
import type { MarketplaceFees } from './marketplaceFees';
import type { Model502 } from './model502';
import type { Model503Orderbook } from './model503Orderbook';
import type { Model503OrderKind } from './model503OrderKind';

export interface Model503 {
  /** If true, royalty amounts and recipients will be set automatically. */
  automatedRoyalties?: boolean;
  currency?: string;
  customRoyalties?: CustomRoyalties;
  /** Amount seller is willing to sell for Dutch auction in the largest denomination for the specific currency. Example: `2000000000000000000` */
  endWeiPrice?: string;
  /** Unix timestamp (seconds) indicating when listing will expire. Example: `1656080318` */
  expirationTime?: string;
  fees?: Model448;
  /** Unix timestamp (seconds) indicating when listing will be listed. Example: `1656080318` */
  listingTime?: string;
  marketplaceFees?: MarketplaceFees;
  /** Optional. Set a custom nonce */
  nonce?: string;
  options?: Model502;
  /** Orderbook where order is placed. Example: `Reservoir` */
  orderbook?: Model503Orderbook;
  /** Optional API key for the target orderbook */
  orderbookApiKey?: string;
  /** Exchange protocol used to create order. Example: `seaport-v1.5` */
  orderKind?: Model503OrderKind;
  /** Quantity of tokens user is listing. Only compatible with ERC1155 tokens. Example: `5` */
  quantity?: number;
  /** Set a maximum amount of royalties to pay, rather than the full amount. Only relevant when using automated royalties. 1 BPS = 0.01% Note: OpenSea does not support values below 50 bps. */
  royaltyBps?: number;
  /** Optional. Random string to make the order unique */
  salt?: string;
  /** Address of wallet taking the private order. Example: `0xF296178d553C8Ec21A2fBD2c5dDa8CA9ac905A00` */
  taker?: string;
  /** Filter to a particular token. Example: `0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63:123` */
  token: string;
  /** Amount seller is willing to sell for in the smallest denomination for the specific currency. Example: `1000000000000000000` */
  weiPrice: string;
}
