/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model353Kind } from './model353Kind';
import type { Model352 } from './model352';

export interface Model353 {
  attributeCount?: number;
  key: string;
  kind: Model353Kind;
  maxRange?: number;
  minRange?: number;
  values?: Model352;
}
