/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model260Kind } from './model260Kind';

export interface Model260 {
  /** Time when added to indexer */
  createdAt?: string;
  id?: number;
  kind?: Model260Kind;
  previousPrice?: number;
  txHash?: string;
  /** Time when added on the blockchain. */
  txTimestamp?: number;
}
