/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Items } from './items';
import type { Model148Kind } from './model148Kind';

export interface Model148 {
  action: string;
  description: string;
  id: string;
  items: Items;
  kind: Model148Kind;
}
