/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Exclusions } from './exclusions';
import type { Model474FillType } from './model474FillType';
import type { RawOrder } from './rawOrder';

export interface Model474 {
  /** Collection to buy. */
  collection?: string;
  /** Only consider orders from this source. */
  exactOrderSource?: string;
  exclusions?: Exclusions;
  /** Optionally specify a particular fill method. Only relevant when filling via `collection`. */
  fillType?: Model474FillType;
  /** Optional order id to fill. */
  orderId?: string;
  /** If there are multiple listings with equal best price, prefer this source over others.
NOTE: if you want to fill a listing that is not the best priced, you need to pass a specific order id or use `exactOrderSource`. */
  preferredOrderSource?: string;
  /** Quantity of tokens to buy. */
  quantity?: number;
  rawOrder?: RawOrder;
  /** Token to buy. */
  token?: string;
}
