/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { BuyIn } from './buyIn';
import type { Model484 } from './model484';

export interface Model517 {
  buyIn?: BuyIn;
  contract?: string;
  currency?: string;
  currencyDecimals?: number;
  currencySymbol?: string;
  feesOnTop?: Model484;
  /** Chain id buying from */
  fromChainId?: number;
  gasCost?: string;
  orderId?: string;
  quantity?: number;
  quote?: number;
  rawQuote?: string;
  source?: string;
  tokenId?: string;
  totalPrice?: number;
  totalRawPrice?: string;
}
