/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model157 } from './model157';
import type { Model159 } from './model159';
import type { Source } from './source';
import type { Model374 } from './model374';

export interface Model377 {
  context?: Model157;
  createdAt?: string;
  feeBreakdown?: Model159;
  floorDifferencePercentage?: number;
  id?: string;
  maker?: string;
  price?: number;
  source?: Source;
  token?: Model374;
  validFrom?: number;
  validUntil?: number;
  value?: number;
}
