/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model362Kind } from './model362Kind';
import type { Model361 } from './model361';

export interface Model362 {
  /** Number of possible attribute kinds */
  attributeCount?: number;
  /** Case sensitive */
  key: string;
  kind: Model362Kind;
  maxRange?: number;
  minRange?: number;
  values?: Model361;
}
