/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type Model148Kind = typeof Model148Kind[keyof typeof Model148Kind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Model148Kind = {
  signature: 'signature',
  transaction: 'transaction',
} as const;
