/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Exclusions } from './exclusions';
import type { Model525 } from './model525';

export interface Model526 {
  /** Only consider orders from this source. */
  exactOrderSource?: string;
  exclusions?: Exclusions;
  /** Optional order id to sell into. */
  orderId?: string;
  /** Quantity of tokens to sell. */
  quantity?: number;
  rawOrder?: Model525;
  /** Token to sell. */
  token: string;
}
