/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model531 } from './model531';
import type { Model532Kind } from './model532Kind';

export interface Model532 {
  action: string;
  description: string;
  /** Returns `auth` or `nft-approval` */
  id: string;
  items: Model531;
  /** Returns `signature` or `transaction`. */
  kind: Model532Kind;
}
