/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type Model421Orderbook = typeof Model421Orderbook[keyof typeof Model421Orderbook];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Model421Orderbook = {
  reservoir: 'reservoir',
  opensea: 'opensea',
  'looks-rare': 'looks-rare',
  x2y2: 'x2y2',
} as const;
