/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model461 } from './model461';
import type { Model462Kind } from './model462Kind';

export interface Model462 {
  action: string;
  description: string;
  items: Model461;
  kind: Model462Kind;
}
