/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Metadata } from './metadata';
import type { Model24 } from './model24';
import type { Model19 } from './model19';
import type { FloorSale } from './floorSale';
import type { FloorSaleChange } from './floorSaleChange';
import type { LastBuy } from './lastBuy';
import type { MintStages } from './mintStages';
import type { Model21 } from './model21';
import type { Model17 } from './model17';
import type { SalesCount } from './salesCount';
import type { SampleImages } from './sampleImages';
import type { Model20 } from './model20';
import type { Volume } from './volume';
import type { Model22 } from './model22';

export interface Model26 {
  allRoyalties?: Metadata;
  attributes?: Model24;
  banner?: string;
  /** true or false */
  collectionBidSupported?: boolean;
  /** Returns `erc721`, `erc1155`, etc. */
  contractKind?: string;
  /** Time when added to indexer */
  createdAt?: string;
  description?: string;
  discordUrl?: string;
  externalUrl?: string;
  floorAsk?: Model19;
  floorSale?: FloorSale;
  floorSaleChange?: FloorSaleChange;
  /** Collection id */
  id?: string;
  image?: string;
  lastBuy?: LastBuy;
  mintedTimestamp?: number;
  mintStages?: MintStages;
  name?: string;
  /** Total tokens currently on sale. */
  onSaleCount?: string;
  openseaVerificationStatus?: string;
  /** Unique number of owners. */
  ownerCount?: number;
  primaryContract?: string;
  rank?: Model21;
  royalties?: Model17;
  salesCount?: SalesCount;
  sampleImages?: SampleImages;
  /** Open Sea slug */
  slug?: string;
  /** Total tokens within the collection. */
  tokenCount?: string;
  tokenSetId?: string;
  topBid?: Model20;
  twitterUsername?: string;
  volume?: Volume;
  volumeChange?: Model22;
}
