/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model133Kind } from './model133Kind';

export interface Model133 {
  /** Time when added to indexer */
  createdAt?: string;
  id?: number;
  kind?: Model133Kind;
  txHash?: string;
  /** Time when added on the blockchain. */
  txTimestamp?: number;
}
