/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Price } from './price';
import type { Model45 } from './model45';

export interface Model94 {
  /** Can be higher than 1 if erc1155. */
  amount?: string;
  batchIndex?: number;
  block?: number;
  from?: string;
  isDeleted?: boolean;
  logIndex?: number;
  price?: Price;
  timestamp?: number;
  to?: string;
  token?: Model45;
  txHash?: string;
  /** Time when last updated in indexer */
  updatedAt?: string;
}
