/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Metadata } from './metadata';
import type { FloorAskPrices } from './floorAskPrices';
import type { Model452Status } from './model452Status';

export interface Model452 {
  data?: Metadata;
  orderIndexes?: FloorAskPrices;
  /** Returns `complete` or `incomplete` */
  status: Model452Status;
  tip?: string;
}
