/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model495 } from './model495';

export interface Model496 {
  /** Chain where orders were created */
  chainId: number;
  /** Address of wallet cancelling the orders */
  makerAddress: string;
  orders: Model495;
}
