/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model331 } from './model331';
import type { Model333 } from './model333';

export interface Model334 {
  floorAskPrice?: Model331;
  id?: string;
  imageUrl?: string;
  isSpam?: boolean;
  metadataDisabled?: boolean;
  name?: string;
  openseaVerificationStatus?: string;
  royalties?: Model333;
  royaltiesBps?: number;
  /** Open Sea slug */
  slug?: string;
  symbol?: string;
}
