/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model554 } from './model554';

/**
 * Params that can be passed in order to override existing ones, to disable override pass null
 */
export interface Model555 {
  bannerImageUrl?: string;
  creator?: string;
  description?: string;
  discordUrl?: string;
  externalUrl?: string;
  imageUrl?: string;
  name?: string;
  royalties?: Model554;
  twitterUrl?: string;
}
