/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model385Method } from './model385Method';
import type { Model384 } from './model384';

export interface Model385 {
  apiKey?: string;
  duration?: number;
  method?: Model385Method;
  payload?: Model384;
  points?: number;
  pointsToConsume?: number;
  /** The route for which the rule is created */
  route: string;
  tier?: number;
}
