/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

/**
 * Exchange protocol used to create order. Example: `seaport-v1.5`
 */
export type Model444OrderKind = typeof Model444OrderKind[keyof typeof Model444OrderKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Model444OrderKind = {
  'zeroex-v4': 'zeroex-v4',
  seaport: 'seaport',
  'seaport-v14': 'seaport-v1.4',
  'seaport-v15': 'seaport-v1.5',
  'looks-rare': 'looks-rare',
  'looks-rare-v2': 'looks-rare-v2',
  x2y2: 'x2y2',
} as const;
