/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model545 } from './model545';

export interface Model546 {
  /** Whether to disable or reenable the metadata. Defaults to true (disable) */
  disable?: boolean;
  tokens: Model545;
}
