/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model106 } from './model106';
import type { Price } from './price';
import type { Metadata } from './metadata';

export interface Model132 {
  contract?: string;
  criteria?: Model106;
  /** Order Id */
  id?: string;
  isDynamic?: boolean;
  kind?: string;
  maker?: string;
  nonce?: string;
  price?: Price;
  /** With ERC1155s, quantity can be higher than 1 */
  quantityRemaining?: number;
  rawData?: Metadata;
  source?: string;
  status?: string;
  validFrom?: number;
  validUntil?: number;
}
