/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model100 } from './model100';
import type { Source } from './source';
import type { Model99 } from './model99';

export interface Model222 {
  amount?: number;
  batchIndex?: number;
  collection?: Model100;
  createdAt?: string;
  fromAddress?: string;
  logIndex?: number;
  price?: number;
  source?: Source;
  timestamp?: number;
  toAddress?: string;
  token?: Model99;
  txHash?: string;
  type?: string;
}
