/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model49OrderSide } from './model49OrderSide';
import type { Model45 } from './model45';

export interface Model49 {
  amount?: string;
  batchIndex?: number;
  currency?: string;
  currencyPrice?: number;
  fillSource?: string;
  from?: string;
  id?: string;
  logIndex?: number;
  orderKind?: string;
  orderSide?: Model49OrderSide;
  orderSource?: string;
  orderSourceDomain?: string;
  price?: number;
  saleId?: string;
  timestamp?: number;
  to?: string;
  token?: Model45;
  txHash?: string;
  usdPrice?: number;
  washTradingScore?: number;
}
