/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type Model418Kind = typeof Model418Kind[keyof typeof Model418Kind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Model418Kind = {
  opensea: 'opensea',
  'zeroex-v4': 'zeroex-v4',
  seaport: 'seaport',
  x2y2: 'x2y2',
} as const;
