/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model478 } from './model478';
import type { Model479Kind } from './model479Kind';

export interface Model479 {
  action: string;
  description: string;
  id: string;
  items: Model478;
  kind: Model479Kind;
}
