/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

/**
 * Currency to buy all listings in.
 */
export type Model468Currency = typeof Model468Currency[keyof typeof Model468Currency];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Model468Currency = {
  '0x0000000000000000000000000000000000000000': '0x0000000000000000000000000000000000000000',
} as const;
