/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model287 } from './model287';
import type { LastBuy } from './lastBuy';
import type { Model288 } from './model288';

export interface Model289 {
  collection?: Model287;
  contract?: string;
  image?: string;
  kind?: string;
  lastAppraisalValue?: number;
  lastBuy?: LastBuy;
  lastSell?: LastBuy;
  media?: string;
  name?: string;
  rarityRank?: number;
  rarityScore?: number;
  tokenId?: string;
  topBid?: Model288;
}
