/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model366 } from './model366';
import type { Model344 } from './model344';
import type { SampleImages } from './sampleImages';
import type { TopBid } from './topBid';

export interface Model367 {
  floorAskPrices?: Model366;
  /** Case sensitive */
  key: string;
  lastBuys?: Model344;
  lastSells?: Model344;
  /** Token count with this attribute on sale. */
  onSaleCount: number;
  sampleImages?: SampleImages;
  /** Total token count with this attribute. */
  tokenCount: number;
  topBid?: TopBid;
  /** Case sensitive */
  value: string;
}
