/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Attribute } from './attribute';
import type { Model420 } from './model420';
import type { Model421Orderbook } from './model421Orderbook';

export interface Model421 {
  attribute?: Attribute;
  collection?: string;
  isNonFlagged?: boolean;
  order?: Model420;
  orderbook?: Model421Orderbook;
  /** Optional API key for the target orderbook */
  orderbookApiKey?: string;
  permitId?: string;
  permitIndex?: number;
  /** The source domain */
  source?: string;
  tokenSetId?: string;
}
