/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model488 } from './model488';
import type { Model489OrderKind } from './model489OrderKind';

export interface Model489 {
  blurAuth?: string;
  maker?: string;
  /** Optional. Set custom gas price */
  maxFeePerGas?: string;
  /** Optional. Set custom gas price */
  maxPriorityFeePerGas?: string;
  orderIds?: Model488;
  orderKind?: Model489OrderKind;
  token?: string;
}
