/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

/**
 * Choose a specific swapping provider when buying in a different currency (defaults to `uniswap`)
 */
export type Model476SwapProvider = typeof Model476SwapProvider[keyof typeof Model476SwapProvider];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Model476SwapProvider = {
  uniswap: 'uniswap',
  '1inch': '1inch',
} as const;
