/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { Model151 } from './model151';
import type { Metadata } from './metadata';
import type { Price } from './price';
import type { Model154Side } from './model154Side';

export interface Model154 {
  contract?: string;
  createdAt: string;
  expiration: number;
  feeBps?: number;
  feeBreakdown?: Model151;
  id: string;
  kind: string;
  maker: string;
  metadata?: Metadata;
  price?: Price;
  rawData?: Metadata;
  side: Model154Side;
  source?: string;
  status?: string;
  taker: string;
  tokenSetId: string;
  tokenSetSchemaHash: string;
  updatedAt: string;
  validFrom: number;
  validUntil: number;
}
