/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

/**
 * Type of auth
 */
export type Model443Kind = typeof Model443Kind[keyof typeof Model443Kind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Model443Kind = {
  blur: 'blur',
  erc721c: 'erc721c',
  opensea: 'opensea',
} as const;
