/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */
import type { PostAdminApikeysMetricsBodyGranularity } from './postAdminApikeysMetricsBodyGranularity';
import type { PostAdminApikeysMetricsBodyGroupBy } from './postAdminApikeysMetricsBodyGroupBy';

export type PostAdminApikeysMetricsBody = {
  /** Get metrics before a particular time (allowed format YYYY-MM-DD HH:00) */
  endTime?: string;
  /** Return results by either hourly/daily/monthly granularity.<br>Hourly will return time in format YYYY-MM-DDTHH:00:000Z<br>Daily will return time in format YYYY-MM-DDT00:00:000Z<br>Monthly will return time in format YYYY-MM-01T00:00:000Z<br> */
  granularity?: PostAdminApikeysMetricsBodyGranularity;
  /** 1 - All calls per hour/day/month<br>2 - All calls per key per hour/day/month<br>3 - All calls per key per route per hour/day/month<br>4 - All calls per key per route per status code per hour/day/month<br> */
  groupBy?: PostAdminApikeysMetricsBodyGroupBy;
  /** Array API keys */
  keys: string[];
  /** Get metrics after a particular time (allowed format YYYY-MM-DD HH:00)<br>Hourly default to last 24 hours<br>Daily default to last 7 days<br>Monthly default to last 12 months */
  startTime?: string;
};
