/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export interface PostOrderV2Response {
  /** Only available when posting to external orderbook. Can be used to retrieve the status of a cross-post order. */
  crossPostingOrderId?: string;
  crossPostingOrderStatus?: string;
  message?: string;
  orderId?: string;
}
