/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * beam-reservoir API
 * You are viewing the reference docs for the beam-reservoir API.        For a more complete overview with guides and examples, check out the <a href='https://reservoirprotocol.github.io'>Reservoir Protocol Docs</a>.
 * OpenAPI spec version: 5.296.1
 */

export type PostApikeysBody = {
  /** The name of your app */
  appName: string;
  /** An e-mail address where you can be reached, in case of issues, to avoid service disruption */
  email: string;
  /** The website of your project */
  website: string;
};
